### ISSUE TITLE
Having an issue getting rack-honeypot working

### ISSUE THREAD

**Issue by keilmillerjr** [sunlightlabs/rack-honeypot#9]
Hello!

I am using rails 3.2.9. I added `gem 'rack-honeypot' ` to my gemfile and ran bundler. I then added `config.middleware.use "Rack::Honeypot"` in envirnment.rb and got the following error:

```
NoMethodError (undefined method `each' for #<String:0x007fddfcd93b68>):
```

I also tried adding the config line to development.rb and application.rb. Both yielded the same results. Any ideas of what is happening?

Thank you.

**Comment by RandieM** [comment]
I had the same problem and @JDutil 's version of the gem fixed it. Thanks!
